language: android
android:
  components:
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-android-support
  licenses:
    - android-sdk-license-.+
script: ./gradle build check connectedCheck
